[package]
name = "azile-telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio.workspace       = true
axum.workspace        = true
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
anyhow.workspace      = true
chrono.workspace      = true

prometheus             = { workspace = true }
opentelemetry          = { workspace = true }
opentelemetry_sdk      = { workspace = true }
opentelemetry-otlp     = { workspace = true }
tracing-opentelemetry  = { workspace = true }
