-- =============================================================================
-- Migration: 0009_fix_dev_admin_seed
--
-- Migration 0008 seeded the dev admin with:
--   1. Identity inserted with ON CONFLICT (email) DO NOTHING
--   2. Membership inserted for hardcoded UUID '...0010'
--
-- If core_mdm.users already contained an admin@nexus.ai row (with a different
-- UUID), step 1 would skip the insert (leaving password_hash = NULL) and step 2
-- would fail the FK constraint → the entire 0008 transaction would roll back,
-- leaving the tables created but no seed data.
--
-- This migration repairs all possible outcomes:
--   a) identity exists but has NULL password_hash → set correct hash
--   b) identity exists with correct hash but no membership → create membership
--   c) identity doesn't exist → insert it with hash + create membership
--   d) 0008 rolled back entirely → create tables + seed (re-runs that work)
--
-- The password hash below is a pre-computed bcrypt $2b$12$ hash of 'Admin@123'
-- generated by the Rust bcrypt crate (v0.15) so verify_password() accepts it
-- without any prefix conversion.
-- =============================================================================

-- ── 1. Ensure the tables exist (safe no-op if 0008 already created them) ─────

CREATE TABLE IF NOT EXISTS core_mdm.identities (
    identity_id   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    email         CITEXT      NOT NULL UNIQUE,
    password_hash TEXT,
    display_name  TEXT        NOT NULL DEFAULT '',
    avatar_url    TEXT,
    is_verified   BOOLEAN     NOT NULL DEFAULT false,
    verified_at   TIMESTAMPTZ,
    last_login_at TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS core_mdm.tenant_memberships (
    membership_id UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    identity_id   UUID        NOT NULL REFERENCES core_mdm.identities(identity_id) ON DELETE CASCADE,
    tenant_id     UUID        NOT NULL REFERENCES core_mdm.tenants(tenant_id)      ON DELETE CASCADE,
    role          TEXT        NOT NULL DEFAULT 'viewer',
    status        TEXT        NOT NULL DEFAULT 'active',
    preferences   JSONB       NOT NULL DEFAULT '{}',
    joined_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ,
    UNIQUE(identity_id, tenant_id)
);

-- ── 2. Upsert the dev admin identity ─────────────────────────────────────────
-- If admin@nexus.ai already exists (any UUID): update the hash.
-- If it doesn't exist: insert it with the well-known dev UUID.
--
-- Hash is bcrypt $2b$12$ of 'Admin@123' — compatible with bcrypt::verify().

INSERT INTO core_mdm.identities (
    identity_id,
    email,
    password_hash,
    display_name,
    is_verified,
    verified_at
)
VALUES (
    '00000000-0000-0000-0000-000000000010',
    'admin@nexus.ai',
    '$2b$12$lbLU3nX07tDW6kETsyEIzeAJGnWwdkGK5p5LJs422uB4EJVqIUpJy',
    'System Admin',
    true,
    NOW()
)
ON CONFLICT (email) DO UPDATE
    SET password_hash = EXCLUDED.password_hash,
        is_verified   = true,
        updated_at    = NOW();

-- ── 3. Ensure admin membership exists for the default tenant ──────────────────
-- Resolve the identity by email (handles the case where the UUID differs from
-- '...0010' because 0008 step 4 inserted a different UUID from core_mdm.users).

INSERT INTO core_mdm.tenant_memberships (identity_id, tenant_id, role, status)
SELECT
    i.identity_id,
    '00000000-0000-0000-0000-000000000001'::uuid,
    'super_admin',
    'active'
FROM core_mdm.identities i
WHERE i.email = 'admin@nexus.ai'
ON CONFLICT (identity_id, tenant_id) DO UPDATE
    SET role   = 'super_admin',
        status = 'active';

-- ── 4. Ensure tenant_licenses exists and default tenant has enterprise tier ───

CREATE TABLE IF NOT EXISTS core_mdm.tenant_licenses (
    license_id    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id     UUID        NOT NULL REFERENCES core_mdm.tenants(tenant_id) ON DELETE CASCADE,
    tier          TEXT        NOT NULL DEFAULT 'enterprise'
                              CHECK (tier IN ('trial', 'essentials', 'professional', 'enterprise')),
    status        TEXT        NOT NULL DEFAULT 'active'
                              CHECK (status IN ('active', 'suspended', 'expired', 'trial')),
    max_domains   INTEGER     NOT NULL DEFAULT -1,
    max_records   BIGINT      NOT NULL DEFAULT -1,
    max_stewards  INTEGER     NOT NULL DEFAULT -1,
    features      JSONB       NOT NULL DEFAULT '{}',
    license_key   TEXT        UNIQUE,
    starts_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at    TIMESTAMPTZ,
    trial_ends_at TIMESTAMPTZ,
    notes         TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(tenant_id)
);

INSERT INTO core_mdm.tenant_licenses (
    tenant_id, tier, status, max_domains, max_records, max_stewards, features, notes
)
VALUES (
    '00000000-0000-0000-0000-000000000001',
    'enterprise', 'active', -1, -1, -1,
    '{"matching_semantic":true,"ai_copilot":true,"relationships":true,"domain_policies":true,"data_quality":true,"analytics":true,"governance":true,"distribution":true}'::jsonb,
    'Default tenant — enterprise tier'
)
ON CONFLICT (tenant_id) DO NOTHING;
